---
title: 'expt1: text length and clf accuracy'
subtitle: 'explore data, compare reggie ml versus nn models'
author: '`tjleffel@gmail.com`'
date: '`r Sys.Date()`'
output: html_document
---


### 1. inspect length + label distros 

```{r}
lefftpack::lazy_setup()

(dat <- dplyr::as_tibble(read.csv('data/imdb_decoded.csv')) %>% 
  mutate(label = as.logical(label)) %>% 
  mutate(length_bin = as.factor(length_bin)))

c(`length at 99.7th pctile: ` = quantile(dat$length, .9966), 
  `percentile at length 1000: ` = ecdf(dat$length)(1000))
```


```{r}
# look at length bin boundaries 
table(cut(dat$length, quantile(dat$length), include.lowest=TRUE))

# check that each actual bin corresponds to its appropriate quantile 
all(table(dat$length_bin) == 
      table(cut(dat$length, quantile(dat$length), include.lowest=TRUE)))
```


```{r}
# trim by length a bit to see the length distribution w/o outliers 
plot_dat <- dat %>% 
  # .9966th length pctile = length 1000 -- or: filter(length <= 1000)
  filter(length <= quantile(dat$length, .9966)) 
```


```{r out.width='50%', fig.show='hold'}
plot_dat %>% 
  ggplot(aes(x=length, fill=label)) + 
  geom_density(color='transparent', alpha=.5)

plot_dat %>% 
  ggplot(aes(x=length, fill=length_bin)) + 
  geom_density(color='transparent', alpha=.5) + 
  theme(legend.title=element_text())
```


```{r}
plot_dat %>% 
  ggplot(aes(x=length, fill=length_bin)) + 
  geom_density(color='transparent', alpha=.5) + facet_wrap(~label) + 
  theme(legend.title=element_text())
```


```{r}
dat %>% group_by(length_bin) %>% 
  summarize(prop_yes = mean(as.numeric(label))) %>% ungroup() %>% 
  ggplot(aes(x=length_bin, fill=length_bin, y=prop_yes)) + 
  geom_bar(stat='identity', alpha=.75)
```

```{r}
dat %>% group_by(length_bin, subset) %>% 
  summarize(prop_yes = mean(as.numeric(label))) %>% ungroup() %>% 
  ggplot(aes(x=length_bin, fill=subset, y=prop_yes)) + 
  geom_bar(stat='identity', position='dodge', alpha=.75)


dat %>% group_by(length_bin, subset) %>% count() %>% ungroup() %>% 
  ggplot(aes(x=length_bin, fill=subset, y=n)) + 
  geom_bar(stat='identity', position='dodge', alpha=.75)

```



### 2. evaluate sklearn model performance on 

```{r}
# TODO: START THIS! (PUT STUFF IN RESULTS/ DIR, SEPT22)


```


